substitutions:
  _REGION: europe-west2
  _REPOSITORY: mindgarden
  _IMAGE_NAME: backend
  _SERVICE_NAME: mindgarden
  _FRONTEND_URL: ""  # Will be provided by GitHub Actions
  _REDIRECT_URI: ""  # Will be provided by GitHub Actions

# Custom logs bucket will be provided via --gcs-log-dir flag

steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}', '.']

# Configure Docker to use Google Cloud as a credential helper
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['auth', 'configure-docker', '${_REGION}-docker.pkg.dev']

# Push the container image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '${_SERVICE_NAME}'
  - '--image'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPOSITORY}/${_IMAGE_NAME}'
  - '--region'
  - '${_REGION}'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
  - '--set-env-vars'
  - 'FRONTEND_URL=${_FRONTEND_URL},REDIRECT_URI=${_REDIRECT_URI},ENVIRONMENT=production'
  - '--update-secrets'
  - 'GOOGLE_API_KEY=GEMINI_API_KEY:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,JWT_SECRET=JWT_SECRET:latest'

# Print the URL of the deployed service
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: sh
  args:
  - '-c'
  - |
    echo "***********************"
    echo "Service deployed to: https://$(gcloud run services describe ${_SERVICE_NAME} --region=${_REGION} --format='value(status.url)')"
    echo "***********************"